name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}  # Remove this line
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  # Remove this line
      - run: npm i
      - run: npm run build

  test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}  # Remove this line
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  # Remove this line
      - run: npm i
      - run: npm test
      
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
