name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm i
      - run: npm run build

  test-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm i
      - run: npm test

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
